fail_fast: true
repos:
- repo: local
  hooks:
  - id: pytest
    name: pytest
    entry: pipenv run pytest
    pass_filenames: false
    language: system

  - id: mypy
    name: mypy
    entry: pipenv run mypy drel
    pass_filenames: false
    language: system

  - id: pylint
    name: pylint
    entry: pipenv run pylint drel
    pass_filenames: false
    language: system

  - id: black
    name: black
    entry: pipenv run black drel
    pass_filenames: false
    language: system

